import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [clientId, setClientId] = useState('');
  const [redirectURI, setRedirectURI] = useState('https://notion-auth.vercel.app');

  const link = `https://api.notion.com/v1/oauth/authorize?client_id=${clientId}&redirect_uri=${redirectURI}%2Fauth%2Fnotion%2Fcallback&response_type=code`;
  
  const startAuth = (e) => {
    e.preventDefault();

    window.open(link, '_blank')

  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        display: 'flex',
        justifyContent: 'center'
      }}>

      <form onSubmit={startAuth}>
        
      <input required style={{
        width: '75%',
        marginBottom: '1rem'
      }} value={clientId} onChange={e => setClientId(e.target.value)} placeholder="Enter client id"  />
      <input required style={{
        width: '75%',
        marginBottom: '1rem'
      }}  value={redirectURI} onChange={e => setRedirectURI(e.target.value)} placeholder="Enter redirect uri"  />

      <div>{link}</div>

      <button type="submit" style={{
        margin: '1rem'
      }}  onClick={startAuth}>Start Auth</button>
</form>
      </div>

      

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
